### ISSUE TITLE
'MESSAGE-GLOBIOM 1.0|ADVANCE_*' and 'MESSAGE-GLOBIOM 1.0|EMF33_*' CCS accounting inconsistency 

### ISSUE THREAD

**Issue by zacharyschmidt** [iiasa/ipcc_sr15_scenario_analysis#11]
For `MESSAGE-GLOBIOM 1.0|ADVANCE_*` and `MESSAGE-GLOBIOM 1.0|EMF33_*`, the timeseries
`Carbon Sequestration|CCS` is not equal to the sum of the two CCS subcategories, `Carbon Sequestration|CCS|Biomass` and `Carbon Sequestration|CCS|Fossil`.

**Comment by danielhuppmann** [comment]
Thanks @zacharyschmidt for raising this issue! I took the liberty of editing the description for cleaner formatting.

This issue is not an accounting error, but a problem of not all data for sub-categories being released by modelling teams, and of changing variable definitions across projects. The difference in this case is due to CCS from Industrial Processes (in particular cement production), which is reported separately by `MESSAGE-GLOBIOM` - but the related timeseries was not included in the variable template for the IAMC 1.5°C (i.e., the IPCC SR15) scenario ensemble.

Closing this issue, as it is not an error and there are currently no plans to extend the variable template for the *IAMC 1.5°C scenario ensemble*.
